language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: KhTwpgIV55bMW3mZ1b/W+oKYbfZOsdDj6a2poCD0+lGH7QoX/gGzwrSVb47YBxTTIggXZLXPeDnvK0GgF2rSa9OJO7uakBCSodpWzhSqXeNRfvZkg4cdPnpmx9M1YgcJLrZIJlRznDr5Wps+OxhZIevaDxOu9mHwrDf9+ywl74q/KTf+r4drbBThGVZJrlKxKWkGv1FujdAHINneGz0t+8XnXuXXvvdMHPh1lcFVsQL00pfuZxb0St3UnTElW7ngqufTpDUwj03yhBGRgGMr8tDXkqORPXD4M2keztKDkvq6QbYVC2QVTRBejh3ERINxEaJjLkVdQegXD39a3PTFLB2Rxv51DUV+a/ewWJO0a9e62qr6kZJWtC6UJw1SobmVbf4Skz/lNRBM+4I3BfhZQ0oVNeoQrVnMOdS6rQ2bczZlcebwUlDwWeN8SU44ToYh43iMSS8BV/kZ7jA1sFEQ/NbfXmrB2iZMBYQ+HRtgOaHYcd4a+zVDAxiEej4Ba0B7XaJqgFCZ4ihc0nTyyahMmc10gRj+9ewAjQw5PrDsNuh1KvIzmSm6B3Okpf6FV3E9yfZnXOBMO5mjS8tgSPSPkOzXhyDc9KYSE707Q5d1uLYz9O3iisZgdta8x5k5OLQzuamxn9EMAAqeKCiM62eaO9VLpHyaY/pAFb6evrzZmEw=
  app: citibiker
after_script:
  - npm run coveralls
